banking
sunmario/my_code pull request #1
Opened 2021-06-07 14:44 UTC by sunmario

check this please 👉🏻👈🏻

2021-06-07 18:37 UTC, lilSpeedwagon requested changes
Коммент сразу ко всему файлу
Постарайся не использоваться короткие имена переменных типа mo, cur и т.д. (особенно если это члены класса)
Так и самой проще запутаться, и читающим код сложнее разобраться

2021-06-07 18:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        self.new_id = self.cur.fetchone()[0]
Всю работу с БД предлагаю вынести в отдельный класс и положить его как поле в Bank.
Таким образом мы:
1. отделим низкоуровневую логику работы с БД от логики обработки запросов клиента
2. локализуем работу с БД в одном месте, что упростит рефакторинг кода и поиск ошибок

2021-06-07 18:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        if self.luhn_check(trans_number):
Обязательно ли проверять валидность номера? Если его нет в базе, то операция все равно не будет выполнена. Не предлагаю убирать это, просто спрашиваю

2021-06-07 18:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                    cur_bal1 = cur_bal1 - int(mo)
Тут уже большой уровень вложенности if/else
Этого можно делая "if (is_bad()) return" вместо if/else.
например:
```suggestion
                if int(mo) > cur_bal1: 
                    print("Not enough money!\n")
                    return
                cur_bal1 = cur_bal1 - int(mo)
                ...
```
Это можно сделать вообще для всех проверок валидности

2021-06-07 18:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            check = "select * from card where number = {}".format(self.cur_acc)
Раз ты получаешь именно баланс, то можно вместо '*' подставить интересующий тебя столбец. Тогда не придется делать странную штуку вроде `query[3]`

2021-06-07 18:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +    def get_balance(self, cardb):
check_balance() и get_balance() вроде бы делают одно и тоже. Может оставить только один из них?

2021-06-07 18:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        pin_input = input("Enter your PIN:")
Уже где то тут писал про то, что этот ввод/вывод лучше унести в main()
В идеале внутри таких классов как Bank вообще не должно быть print'ов
Ошибки можно выводить наружу через исключения и в main просто делать print сообщения, а такие вещи как баланс просто возвращать из соответствующих методов числом.
Метод login() может, например, возвращать bool как результат входа.

2021-06-07 18:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                    upd_t = "update card set balance = {l[0]} where number = {l[1]};".format(l=[cur_bal2, trans_number])
Такую штуку как перевод денег лучше делать одной транзакцией в БД
То есть commit() лучше оставить только один в конце
Иначе может возникнуть ситуация, когда с одного счета деньги списаны, а потом было брошено исключение и на второй счет они не попали. В итоге они вообще потерялись.

2021-06-09 13:48 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +    def get_balance(self, cardb):
Нет, мне нужно именно две функции, потому что гет мне позволяет легко взять значение баланса в текущий момент, а чек чтобы пользователю выводить на экран, хотя возможно что можно просто делать гет + подписывать текстом именно когда пользователь просит баланс

2021-06-09 13:49 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +            check = "select * from card where number = {}".format(self.cur_acc)
а, я на секунду подумала, что мне нужны все столбцы раз я чекаю условие, чет тупанула

2021-06-09 13:50 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +            self.con = sqlite3.connect(file)
такой вопрос надо отдельно посмотреть, я даже не думала если честно.

2021-06-09 13:52 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +class Account(Bank):
мне надо снова продумать структуру абстракций на самом деле, может быть потом скину тебе что придумала в виде схемы или типо того
скорее тогда класс будет не банк а просто мейн и в нем все происходит
но я ещё не разобралась

2021-06-09 13:52 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +    def luhn(self):
да, пайчарм мне это тоже предлагал и там появляется @static, но я пока не разобралась че там

2021-06-09 13:53 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +    def luhn(self):
Это хорошее замечание, добавлю комментарий-документацию

2021-06-09 13:54 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +"""
Это я наверное торопилась и хотела сразу записать твои замечания, ещё до того как ты сказал, что черех гитхаб все откоммментишь

2021-06-12 10:16 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +    def luhn(self):
Тогда прочитай про статические методы, там не супер сложно
https://younglinux.info/oopython/staticmethod

2021-06-12 10:18 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +class Account(Bank):
Класс для мейна я думаю не нужен
А вот банк лучше оставить. Банк реализует логику работы с разными банковскими счетами. Логика и данные каждого счета сидят в классе Account. А хранение аккаунтов может обрабатываться классом для работы с БД.
В итоге получается 3 класса: Bank, Account, DbAdapter.

2021-06-12 10:21 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +    def get_balance(self, cardb):
Ну типо да. В main у тебя есть цикл ввода-вывода. Там пользователь хочет посмотреть баланс. Ты делаешь:
```current_balance = bank.get_balance(card)
print('your balance: ' + str(current_balance))```

2021-06-14 09:46 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +        if self.luhn_check(trans_number):
Это кажется было по заданию, но звучит логично

2021-06-14 10:04 UTC, sunmario commented
на данный момент:
обработала замечание по именам переменных
насчет доступа к файлам
сделала методы статическими

впереди ещё
переделать структуру абстракций
разобраться с мптодами бд и отделить их от класса банка и аккаунта

2021-06-27 13:07 UTC, sunmario commented
тут вроде учла и проверила все предыдущие замечания, надо ещё доделать функцию перевода денег

2021-06-27 15:47 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            l=[str((self.new_id + 1)), str(number), str(pin), str(balance)])
Здесь ты получаешь id из таблицы, а потом инкрементишь его чтобы вставить новое значение. Но SQL умеет использовать автоинкрементируемые поля. То есть ты просто не указываешь поле id при вставке, а SQL сам добавляет туда единичку. Вот тут есть пример: https://www.w3schools.com/sql/sql_autoincrement.asp#:~:text=The%20MS%20SQL%20Server%20uses,IDENTITY(10%2C5)%20.
Таким образом можно убрать логику инкремента id и оставить это для СУБД

2021-06-27 15:47 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        res = self.db.db_get_balance(self.current_account)
Может здесь в try-except завернуть? Просто ты делаешь login и расчитываешь что такой аккаунт точно существует и есть в бд. Скорее всего будет работать, но я бы добавил просто на всякий случай здесь перехват исключения и вывод чего-то типа "unable to fetch balance". Не обязательно исправлять, но подумай про это

2021-06-27 15:47 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                print("Such a card does not exist.\n") #может тут эксепшн
Да, тут лучше бросить исключение и вывести информацию уже там где ты вызываешь эту функцию

2021-06-27 15:47 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                #maybe i should update with add_income
Возможно, этот комментарий устарел

2021-06-27 15:47 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                self.db_update_balance(money,trans_number)
А что произойдет если второго аккаунта не существует? Или, например, внезапно пропадет соединение с бд между двумя операциями? Я думаю в этом методе нужно сделать что то вроде транзакции
То есть чтобы операция либо была выполнена целиком, либо не выполнена вообще
Прочитай в интернете про транзакции и про гарантии исключений

2021-06-27 19:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        self.exit = False
Вот это вроде нигде не используется. Может удалить?

2021-06-27 19:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        print("Your card PIN:\n{}\n".format(pin))
Может все таки вынесешь IO наружу? Можно возвращать отсюда тьюпл с номером карты и пином или исключение если чето пошло не так

2021-06-27 19:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            return False
У тебя чет метод получается слишком странный
Если карты нет, то возвращает boolean, а если есть, то вложенный список или типо того
Предлагаю разбить это на два метода
is_cart_exist() -> boolean и get_card_info() -> {string, string}
Вот здесь кстати пригодился бы твой класс Account, который ты удалила. Он мог бы просто хранить в себе 2-3 поля про номер карты, пин и баланс

2021-06-27 19:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            print("Wrong card number or PIN!\n")
Вот тут мне вообще не нравится че происходит
1. query вообще непонятная переменная
2. в ней может лежать False, а может список списков
3. многоуровневая вложенность
4. printы которые бы вынести наружу

2021-06-27 19:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        print("Income was added!\n")
Опять же, вынеси отсюда IO и передавай сумму как аргумент в метод

2021-06-27 19:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +    def db_add_account(self,number,pin):
Микрозамечение, но как мне кажется, нет смысла добавлять к каждому методу префикс db. Типо ты и так в классе который про базу данных

2021-06-27 19:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                print("Such a card does not exist.\n")
Здесь можно для упрощения сделать return и все что дальше не пихать в else

2021-06-27 19:37 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        exit_bool = True
Обычно такие логические переменные называют с глаголами is, has, need и тд
В данном случае можно назвать need_exit
Ну и странная логика в названии  у тебя. Создается ощущение, что когда exit_bool = True, то нужно выйти, а у тебя наоборот.

2021-06-28 15:35 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +        self.cursor.execute('select max(id) from card')
хорошо, я скорее всего какой-то из запросов копипастила и не исправила кейс

2021-06-28 15:37 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +                print("Such a card does not exist.\n") #может тут эксепшн
то есть тогда при вызове этой функции если результат это исключение/сообщение об исключении то делаю/вывожу такую-то штуку?

2021-06-28 15:38 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +        self.exit = False
я думала инит всегда нужен
мы же когда создаем экзампляр класса банк то надо подключение к бд?

2021-06-28 15:38 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +        print("Your card PIN:\n{}\n".format(pin))
Хорошо, думаю ещё раз переделаю, после комментария про работу сервиса это понятнее стало

2021-06-28 15:40 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +    def db_add_account(self,number,pin):
ну это мне чтобы различать их

2021-06-29 17:21 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                print("Such a card does not exist.\n") #может тут эксепшн
Ну просто оберни вызов в try-except, а здесь можно бросить исключение с сообщением о том что пошло не так
raise RuntimeError("Such a card does not exist.\n")

2021-06-29 17:22 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        self.exit = False
Не, комментарий именно к строке ```self.exit = False```
Сама переменная не используется нигде

2021-06-29 17:25 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        res = self.db.db_get_balance(self.current_account)
Да не, я думаю про прятать методы тут не при чем
Просто мы очень сильно рассчитываем на ситуацию, когда в бд уже есть такой аккаунт под которым мы вошли. Ну логично. Но иногда стоит подстраховаться и обработать даже такие странные случаи
Править или нет - на твое усмотрение

2021-06-29 18:46 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +            return False
а смысл его хранить
может хранить словарь текущего пользователя? типо когда логин он селект из бд
потом обновляет штуки по ходу операций

2021-06-29 18:51 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +        res = self.db.db_get_balance(self.current_account)
почему именно расчитываем? если бы его не было, мы бы не смогли проверить номер карты и пин для входа
или ты имеешь в виду что это должна быть функция не для залогиненого пользователя а для всех?
просто если пользователь зашел то конкретно он имеет доступ только к своему балансу

2021-06-30 18:22 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            return False
Ну можно и так
То есть завести поля current_card, current_balance
Но тем не менее, метод странный. Давай переделаем?

2021-06-30 18:23 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        res = self.db.db_get_balance(self.current_account)
Ладно, оставь так
Потом как нибудь расскажу пример и что я имел ввиду

2021-07-01 12:31 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +            l=[str((self.new_id + 1)), str(number), str(pin), str(balance)])
Я скорее всего использовала логику из оригинального задания где про это не говорилось и с авто инкрементом не принимал

2021-07-01 12:45 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +            return False
короче нам нужен созвон похоже чтобы все обсудить, а то я иногда забываю что ты говорил/писал(((

2021-07-01 12:47 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +                print("Such a card does not exist.\n")
вроде про это было в той статье
типо если чек фолс то мы ретерн сообщение
а дальше без элза весь остальной код?

2021-07-03 10:22 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                print("Such a card does not exist.\n")
да, а еще вместо `check == False` можно писать `not check` или` !check`

2021-07-05 12:34 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +                self.db_update_balance(money,trans_number)
вот я почитала про распределенные вычисления
но не поняла как это применить
и вот по тем твоим замечаниям тоже вроде все подходит:
сначала вводится номер карты куда переводить и проверяется есть ли она
только при существовании карты + достаточном балансе происходит перевод
про транзакции я залезлы в документацию модуля который использую:
![image](https://user-images.githubusercontent.com/32369905/124472107-642e5600-dda6-11eb-8e94-dff62e480d49.png)
так что вроде это и есть транзакции
типо сначала я исполняю запросы через execute
а потом подтверждаю коммит

2021-07-05 18:00 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            return False
А что будет если карта существует, но неверен пин? Насколько я понимаю, в таком случае мы выйдем из внутреннего if, но не дойдем в `return False` и в итоге вообще ничего не вернем из функции
Проще все решается удалением else в конце

2021-07-05 18:00 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            return False
А еще я чет не уверен нужна ли проверка `info[0] == card_input`, ведь мы и так получили информацию по этой карте

2021-07-05 18:02 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            d = self.bank.do_transfer(trans_number,money)
опять очень содержательные имена переменных
Можно кстати не заводить переменную, а делать `if self.bank.do_transfer(...)`:

2021-07-05 18:03 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                return True
Уже писал про это
Если у тебя внутри if происходит выход из функции (return или raise), то можно else опустить для уменьшения вложенности

2021-07-05 18:05 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +        while not self.need_exit:
Может добавить try-except внутри while? А то, насколько, я понимаю, если ввести неверную цифру или вообще не цифру, то получим IndexError и вывалимся из приложения

2021-07-05 18:13 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                self.db_update_balance(money,trans_number)
Можешь это использовать, но тогда измени метод так, чтобы commit был один после всех операций с бд
Только почему у тебя db_do_transfer вообще нигде не используется, а Bank.transfer повторяет то же самое

2021-07-05 19:16 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +        while not self.need_exit:
да, только там это KeyError, но не суть

2021-07-06 10:05 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +                self.db_update_balance(money,trans_number)
просто по идее все действия для зачисления денег есть в add income и я такая ой ну вот не придется писать снова запросы, а в той функции все что надо было

2021-07-06 19:04 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                self.db_update_balance(money,trans_number)
разберись с этими функциями блин нафиг ::toad::

2021-07-07 18:30 UTC, lilSpeedwagon requested changes

2021-07-07 18:30 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +            return False
Обработай здесь случай когда ```exist is None```. Можно переписать как ```return exist is not None``` или вынести ```return False``` в самый конец функции

2021-07-07 18:30 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                self.add_income(-int(money), self.current_account)
Забыла здесь вызвать ```db_do_transfer``` вместо ```add_income```

2021-07-07 18:44 UTC, sunmario commented on hyperskill_practice/simple_bank/banking.py
> +                self.add_income(-int(money), self.current_account)
ещё я сейчас посмотрела - я зачем-то проверяю баланс и карту куда переводим и в бд и в банке
по идее можно оставить только в бд
потому что там при невыполнении условий сообщения вылазят тоже

2021-07-07 18:46 UTC, lilSpeedwagon commented on hyperskill_practice/simple_bank/banking.py
> +                self.add_income(-int(money), self.current_account)
Да, можно оставить только в бд

2021-07-08 13:20 UTC, lilSpeedwagon approved these changes

2021-07-08 13:20 UTC, merged